export const commonTags = (ogTitle, ogDescription, ogKeywords, ogImage, themeColor) => ([
  { name: 'title', content: ogTitle },
  { name: 'description', content: ogDescription },
  { property: 'og:description', content: ogDescription },
  { property: 'og:image', content: ogImage ? `http:${ogImage.file.url}` : '' },
  { property: 'og:image:secure_url', content: ogImage ? `https:${ogImage.file.url}` : '' },
  { property: 'og:image:width', content: ogImage ? ogImage.file.details.image.width : 0 },
  { property: 'og:image:height', content: ogImage ? ogImage.file.details.image.height : 0 },
  { property: 'og:image:height', content: ogImage ? ogImage.file.details.image.height : 0 },
  { property: 'og:image:type', content: ogImage ? ogImage.file.contentType : '' },
  { property: 'og:image:alt', content: ogImage ? ogImage.description : '' },
  { name: 'keywords', content: ogKeywords },
  { name: 'msapplication-TileColor', content: themeColor },
  { name: 'theme-color', content: themeColor },
])
